jenkins:
  systemMessage: "Jenkins configured automatically by Ansible"
  numExecutors: 2

security:
  realm:
    local:
      allowsSignup: false
      users:
        - id: admin
          password: admin

credentials:
  system:
    domainCredentials:
      - credentials:
          - usernamePassword:
              scope: GLOBAL
              id: "dockerhub"
              username: "${DOCKERHUB_USERNAME}"
              password: "somesecret" # replace with secret in production

unclassified:
  location:
    url: "http://localhost:8080/"
