name: CI/CD Pipeline
on:
  push:
    branches: [main]

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  FRONTEND_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/devops-frontend
  BACKEND_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/devops-backend

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Login to Docker Hub
      - name: Login to Docker Hub
        run: echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

      # Build and push frontend
      - name: Build Frontend
        run: docker build -t $FRONTEND_IMAGE:$GITHUB_SHA -f frontend/Dockerfile frontend/
      - name: Push Frontend
        run: docker push $FRONTEND_IMAGE:$GITHUB_SHA

      # Build and push backend
      - name: Build Backend
        run: docker build -t $BACKEND_IMAGE:$GITHUB_SHA -f backend/Dockerfile backend/
      - name: Push Backend
        run: docker push $BACKEND_IMAGE:$GITHUB_SHA

  # cd:
  #   needs: ci
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: hashicorp/setup-terraform@v2

  #     # Deploy Jenkins
  #     - run: terraform init && terraform apply -auto-approve
  #       env:
  #         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  #     # Get Jenkins IP
  #     - run: echo "JENKINS_IP=$(terraform output -raw jenkins_ip)" >> $GITHUB_ENV

  #     # Wait for Jenkins
  #     - run: |
  #         until curl -s http://$JENKINS_IP:8080/api/json; do
  #           sleep 10
  #         done

  #     # Trigger Jenkins job with frontend/backend tags
  #     - run: |
  #         curl -X POST http://$JENKINS_IP:8080/job/deploy/build \
  #           --user admin:${{ secrets.JENKINS_API_TOKEN }} \
  #           --data-urlencode json='{
  #             "parameter": [
  #               {"name":"FRONTEND_TAG", "value":"$GITHUB_SHA"},
  #               {"name":"BACKEND_TAG", "value":"$GITHUB_SHA"}
  #             ]
  #           }'

  #     # Destroy Jenkins after delay
  #     - run: sleep 600 && terraform destroy -auto-approve
